# data operate
张量表示一个数组，数组可以有多个维度

In [2]:
import torch
x = torch.arange(12)
x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过`shape`访问形状通过`numel`访问元素总数

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

通过`reshape`不改变数量和元素值

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用标准运算符（`+`、`-`、`*`、`\`、`**`）对矩阵进行**按元素**运算

In [6]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

也可以将多个张量`结合`在一起

In [7]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4)) 
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0) , torch.cat((X, Y), dim=1)  #  dim = 0 按行 dim = 1 按列

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

生成`逻辑矩阵`以及`求和`

In [8]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
X.sum()

tensor(66.)

广播机制（broadcasting mechnism）要求维度必须相同

In [10]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
a + b # 运算规则是 将a复制成3，2矩阵 b复制成3，2矩阵

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
import numpy as np
c2w = torch.arange(9).reshape(3,3)
dirs = torch.arange(12).reshape(2,2,3)

c2w, dirs, dirs[..., np.newaxis,:] * c2w

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]]]),
 tensor([[[[ 0,  1,  4],
           [ 0,  4, 10],
           [ 0,  7, 16]],
 
          [[ 0,  4, 10],
           [ 9, 16, 25],
           [18, 28, 40]]],
 
 
         [[[ 0,  7, 16],
           [18, 28, 40],
           [36, 49, 64]],
 
          [[ 0, 10, 22],
           [27, 40, 55],
           [54, 70, 88]]]]))

In [22]:
temp1 = torch.arange(9).reshape(3,3)
temp2 = torch.arange(3)
temp1, temp2, temp1.mv(temp2),temp2[np.newaxis,:]*temp1, torch.sum(temp2[np.newaxis,:]*temp1, -1)

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([0, 1, 2]),
 tensor([ 5, 14, 23]),
 tensor([[ 0,  1,  4],
         [ 0,  4, 10],
         [ 0,  7, 16]]),
 tensor([ 5, 14, 23]))