# 自动求导
创建一个m*n的矩阵


In [77]:
import torch
A = torch.arange(20).reshape(5,4)
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵转置

In [78]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

任何元素二元运算结果都是相同形状的张量

In [79]:
A = torch.arange(20, dtype=torch.float).reshape(5,4)
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

指定张量按某一个轴降维求和

In [80]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [81]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [82]:
A.sum(axis=[0, 1])

tensor(190.)

计算综合或均值时数轴保持不变

In [83]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将A除以sum_A

In [84]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

按照轴计算累计总和

In [85]:
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

矩阵的向量积


In [86]:
x = torch.ones(4, dtype=torch.float32)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 6., 22., 38., 54., 70.]))

矩阵乘法

In [87]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$L_2$范数是向量元素的平方根：$$||x||_2 = \sqrt{\sum_{i=1}^{n} x^2_i}$$

In [88]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)


tensor(5.)

$L_1$范数，是向量元素的绝对值的和：$$||x_i||\sum_{i=1}^{n}|x_i|$$

In [89]:
torch.abs(u).sum() # abs是绝对值

tensor(7.)

f范数：$$||x||_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n} x^2_{ij}}$$

In [90]:
torch.norm(torch.ones((4,9)))


tensor(6.)

# 自动求导


In [91]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

计算y关于x的梯度之前，我们需要一个地方存储梯度

In [92]:
x.requires_grad_(True)
y = 2 * torch.dot(x, x)
y

tensor(6., grad_fn=<SumBackward0>)

调用反向传播计算y关于x每个分量的梯度

In [93]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [95]:
x.grad.zero_() # 使用该函数进行归零
y = x.sum()
y.backward()
x.grad

tensor([0., 0., 0., 0.])


tensor([1., 1., 1., 1.])